# Generated by Django 3.2.7 on 2021-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehtava',
            name='kuvaus',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
