# Generated by Django 3.2.7 on 2021-10-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0002_tehtava_kuvaus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehtava',
            name='otsikko',
            field=models.CharField(max_length=250),
        ),
    ]
